language: node_js
node_js:
  - "8"

before_install:
  - npm install jshint -g
  - npm install mocha -g
  - npm install istanbul -g
  - npm install bower -g

script:
  - npm run lint
  - npm run coverage

after_script:
  - npm run coveralls
