# to install bcrypt
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js
node_js:
  - 4.4.3

before_script:
  - npm install -g jasmine-node
script:
  - npm run test:travis
