############## Commands ##########################
### docker-compose up -d
### docker-compose logs -f
### docker container list

############## Docs ##############################
# https://hub.docker.com/_/couchdb

version: "3.7"
services:
  couchdb:
    build:
      context: ./
      dockerfile: ./Dockerfile-couchdb
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=none
  app:
    depends_on:
      - couchdb
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3183:3183
    environment:
      - FOO=too
