############## Commands ##########################
### docker-compose up -d
### docker-compose logs -f
### docker container list

############## Docs ##############################
# https://hub.docker.com/_/couchdb

version: "3.7"
services:
  couchdb:
    image: couchdb:1.6.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=none
    ports:
      - 5984:5984
      - 6984:6984
  app:
    depends_on:
      - couchdb
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3183:3183
    environment:
      - FOO=too