FROM couchdb:3.5.1

WORKDIR /

COPY etc/* /opt/couchdb/etc/
COPY config/fielddb_debug.* /opt/couchdb/etc/

RUN set +x; \
  curl -Xk PUT https://admin:none@127.0.0.1:6984/_users; \
  curl -Xk PUT https://admin:none@127.0.0.1:6984/_replicator; \
  ls -alt /opt/couchdb/etc; \
  cat /opt/couchdb/etc/local.ini; \
  ls /opt/couchdb/etc/local.d;
